AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Confirmação da conta, valida a token e move as informações de pré-usuário para
  o usuário (validado) no dynamodb
Resources:
  precustomertocustomer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Confirmação da conta, valida a token e move as informações de
        pré-usuário para o usuário (validado) no dynamodb
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /customer/validate
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Environment:
        Variables:
          TABLE_NAME: pre-customer
          TABLE_NAME_CUSTOMER: customer
      Layers:
        - ''
